version: '3.6'
services:
  home:
    image: jjp1023/home:0.1.2
    expose:
      - "3000"
    labels:
      - "traefik.backend=home"
      - "traefik.docker.network=jitsi"
      - "traefik.enable=true"
      - "traefik.basic.port=3000"
      - "traefik.basic.frontend.rule=Host:jiggyjigs.me"
    restart: always
    networks:
      jitsi:
networks:
  jitsi:
    external: true
