---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: apps
  name: home
  labels:
    app: home
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: apps-home-prefix@kubernetescrd
spec:
  rules:
  - host: jiggyjigs.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home
            port:
              number: 3000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: home-prefix
  namespace: apps
spec:
  addPrefix:
    prefix: /home
