---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: apps
  name: home
  labels:
    app: home
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: jiggyjigs.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home
            port:
              number: 3000
        pathRewrite:
          prependPath: /home
        middlewares:
        - name: add-prefix
          namespace: default
  ---
  apiVersion: traefik.containo.us/v1alpha1
  kind: Middleware
  metadata:
    name: add-prefix
    namespace: default
  spec:
    replacePathRegex:
      regex: /
      replacement: /home/
